apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-06-19T01:11:36Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: elbowpay
  name: elbowpay
  namespace: prod
  resourceVersion: "7238"
  uid: b993246d-dfa9-48bc-aead-520513241c64
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.37.171
  clusterIPs:
  - 10.100.37.171
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30468
    port: 1957
    protocol: TCP
    targetPort: 1957
  selector:
    app: elbowpay
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: ab993246ddfa948bcaead520513241c6-2061880808.us-east-1.elb.amazonaws.com
